# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Makefile for Unix & Linux Systems #
# using a GNU C++ compiler #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
	
# compiler flags
# -g --Enable debugging
# -Wall --Turn on all warnings
# -D_USE_FIXED_PROTOTYPES_
# --Force the compiler to use the correct headers
# -ansi --Don't use GNU ext; do use ansi standard.
	
CXX = g++
# CXX_STD = CXX20	
CXXFLAGS = -std=c++17	
	
#Link command:
Rangeshifter: Main.o ../Common/BatchMode.o ../Common/RScore/Cell.o ../Common/RScore/Community.o ../Common/RScore/FractalGenerator.o ../Common/RScore/Genome.o ../Common/RScore/Individual.o ../Common/RScore/Landscape.o ../Common/RScore/Model.o ../Common/RScore/Parameters.o ../Common/RScore/Patch.o ../Common/RScore/Population.o ../Common/RScore/RandomCheck.o ../Common/RScore/RSrandom.o ../Common/RScore/Species.o ../Common/RScore/SubCommunity.o ../Common/Version.o	
	$(CXX) $(CXXFLAGS) Main.o ../Common/BatchMode.o ../Common/RScore/Cell.o ../Common/RScore/Community.o ../Common/RScore/FractalGenerator.o ../Common/RScore/Genome.o ../Common/RScore/Individual.o ../Common/RScore/Landscape.o ../Common/RScore/Model.o ../Common/RScore/Parameters.o ../Common/RScore/Patch.o ../Common/RScore/Population.o ../Common/RScore/RandomCheck.o ../Common/RScore/RSrandom.o ../Common/RScore/Species.o ../Common/RScore/SubCommunity.o ../Common/Version.o -o Rangeshifter	
	
#Compilation commands:
Main.o: Main.cpp	
	$(CXX) $(CXXFLAGS) -c Main.cpp -o Main.o	
	
../Common/BatchMode.o: ../Common/BatchMode.cpp
	$(CXX) $(CXXFLAGS) -c ../Common/BatchMode.cpp -o ../Common/BatchMode.o

../Common/RScore/Cell.o: ../Common/RScore/Cell.cpp
	$(CXX) $(CXXFLAGS) -c ../Common/RScore/Cell.cpp -o ../Common/RScore/Cell.o

../Common/RScore/Community.o: ../Common/RScore/Community.cpp
	$(CXX) $(CXXFLAGS) -c ../Common/RScore/Community.cpp -o ../Common/RScore/Community.o

../Common/RScore/FractalGenerator.o: ../Common/RScore/FractalGenerator.cpp
	$(CXX) $(CXXFLAGS) -c ../Common/RScore/FractalGenerator.cpp -o ../Common/RScore/FractalGenerator.o

../Common/RScore/Genome.o: ../Common/RScore/Genome.cpp
	$(CXX) $(CXXFLAGS) -c ../Common/RScore/Genome.cpp -o ../Common/RScore/Genome.o

../Common/RScore/Individual.o: ../Common/RScore/Individual.cpp
	$(CXX) $(CXXFLAGS) -c ../Common/RScore/Individual.cpp -o ../Common/RScore/Individual.o

../Common/RScore/Landscape.o: ../Common/RScore/Landscape.cpp
	$(CXX) $(CXXFLAGS) -c ../Common/RScore/Landscape.cpp -o ../Common/RScore/Landscape.o

../Common/RScore/Model.o: ../Common/RScore/Model.cpp
	$(CXX) $(CXXFLAGS) -c ../Common/RScore/Model.cpp -o ../Common/RScore/Model.o

../Common/RScore/Parameters.o: ../Common/RScore/Parameters.cpp
	$(CXX) $(CXXFLAGS) -c ../Common/RScore/Parameters.cpp -o ../Common/RScore/Parameters.o

../Common/RScore/Patch.o: ../Common/RScore/Patch.cpp
	$(CXX) $(CXXFLAGS) -c ../Common/RScore/Patch.cpp -o ../Common/RScore/Patch.o

../Common/RScore/Population.o: ../Common/RScore/Population.cpp
	$(CXX) $(CXXFLAGS) -c ../Common/RScore/Population.cpp -o ../Common/RScore/Population.o

../Common/RScore/RandomCheck.o: ../Common/RScore/RandomCheck.cpp
	$(CXX) $(CXXFLAGS) -c ../Common/RScore/RandomCheck.cpp -o ../Common/RScore/RandomCheck.o

../Common/RScore/RSrandom.o: ../Common/RScore/RSrandom.cpp
	$(CXX) $(CXXFLAGS) -c ../Common/RScore/RSrandom.cpp -o ../Common/RScore/RSrandom.o

../Common/RScore/Species.o: ../Common/RScore/Species.cpp
	$(CXX) $(CXXFLAGS) -c ../Common/RScore/Species.cpp -o ../Common/RScore/Species.o

../Common/RScore/SubCommunity.o: ../Common/RScore/SubCommunity.cpp
	$(CXX) $(CXXFLAGS) -c ../Common/RScore/SubCommunity.cpp -o ../Common/RScore/SubCommunity.o

../Common/Version.o: ../Common/Version.cpp
	$(CXX) $(CXXFLAGS) -c ../Common/Version.cpp -o ../Common/Version.o

#make clean
clean:
	rm -f *.o
