# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_from_R <- function(ParMaster, dirpath) {
    .Call('_RangeshiftR_run_from_R', PACKAGE = 'RangeshiftR', ParMaster, dirpath)
}

clear_outPop <- function() {
    invisible(.Call('_RangeshiftR_clear_outPop', PACKAGE = 'RangeshiftR'))
}

